spring:
  datasource:
    druid:
      #监控统计
      filters: stat
      username: root
      password: ENC(NuJH1iRfFmt+oxcHMxyr4g==)
      url: jdbc:mysql://localhost/demo?useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      #配置初始化
      initial-size: 1
      min-idle: 1
      max-active: 20
      #连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  application:
    name: demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


mybatis:
  mapper-locations: classpath:dao/teacher/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
jasypt:
  encryptor:
    password: asdfg







