spring:
  datasource:
    url: jdbc:mysql://localhost/demo?useSSL=false
    username: root
    password: java
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:dao/teacher/*Mapper.xml


swagger:
  enabled: true
  title: oms-API
  description: API文档
  base-package:  com.demo
  base-path: /**
  exclude-path: /error
  version: @project.version@

